### ISSUE TITLE
Log det Jacobian is wrong in Inv1x1Conv

### ISSUE THREAD

**Issue by MokkeMeguru** [jaywalnut310/glow-tts#17]
![image](https://user-images.githubusercontent.com/30849444/84584915-02bae280-ae45-11ea-85e8-a1637f2109a2.png)

So, this log det jacobian is `torch.slogdet(self.weight)`

https://github.com/jaywalnut310/glow-tts/blob/00a482d06ebbffbd3518a43480cd79e7b47ebbe2/modules.py#L228

**Comment by MokkeMeguru** [comment]
And also, 
https://github.com/jaywalnut310/glow-tts/blob/00a482d06ebbffbd3518a43480cd79e7b47ebbe2/modules.py#L212

is something wrong.

If input tensor is [B, C, H, W], log det jacobian is `torch.slogdet(W) * h * w`
So, if input tensor is [B, C, T], log det Jacobian is `torch.slogdet(W) * t`

I think x_mask is [B, C, T], so

```python
torch.sum(x_mask[:, 0:1, :], [2])
```

**Comment by anonymous-repo-tech** [comment]
`slogdet` is exactly the right function, but if the det of the weight is always positive, `logdet` is also okay .

I initialized the det of the weight to be positive as follows:
https://github.com/jaywalnut310/glow-tts/blob/00a482d06ebbffbd3518a43480cd79e7b47ebbe2/modules.py#L200-L203

Because the training process (maximizing log likelihood of data) encourages the determinant to increase, the det of the weight tends to maintain positivity.

The main reason I prefer `logdet` is that it's easier and more stable to calculate than `slogdet`.
Actually, I followed the implementation of WaveGlow:
https://github.com/NVIDIA/waveglow/blob/master/glow.py#L76-L80
https://github.com/NVIDIA/waveglow/blob/d18e0f3cc2ff6bdd41244d7391140accdc41142b/glow.py#L100

**Comment by jaywalnut310** [comment]
`slogdet` is exactly the right function, but if the det of the weight is always positive, `logdet` is also okay .

I initialized the det of the weight to be positive as follows:
https://github.com/jaywalnut310/glow-tts/blob/00a482d06ebbffbd3518a43480cd79e7b47ebbe2/modules.py#L200-L203

Because the training process (maximizing log likelihood of data) encourages the determinant to increase, the det of the weight tends to maintain positivity.

The main reason I prefer `logdet` is that it's easier and more stable to calculate than `slogdet`.
Actually, I followed the implementation of WaveGlow:
https://github.com/NVIDIA/waveglow/blob/master/glow.py#L76-L80
https://github.com/NVIDIA/waveglow/blob/d18e0f3cc2ff6bdd41244d7391140accdc41142b/glow.py#L100

**Comment by MokkeMeguru** [comment]
Thanks your information ! I didn't know positive weight initialization because I didn't see WaveGlow's implementation.

**Comment by MokkeMeguru** [comment]
Can you show me the source reference that slogdet is more stable than logdet ?

**Comment by jaywalnut310** [comment]
> The main reason I prefer `logdet` is that it's easier and more stable to calculate than `slogdet`.

I misunderstood that `logdet` is easier to calculate than `slogdet`, because `logdet` of positive definite matrices is easily formulated. For arbitrary matrices, the two functions  are implemented similarly except the sign info.  Sorry for my misunderstanding, @MokkeMeguru. 

However, for checking training stability, `logdet` can be a good tool. 
Although the determinant of weights are initialized to be positive and the training process encourages the determinant to increase, the determinant can fluctuate positive/negative across zero due to some bad training configurations. 
In that case, `logdet` would make errors that alert you did something wrong, while `slogdet`  wouldn't.

rafaelvalle's mentions in waveglow issues would be helpful:
https://github.com/NVIDIA/waveglow/issues/49#issuecomment-442522418
https://github.com/NVIDIA/waveglow/issues/35#issuecomment-442523005

**Comment by MokkeMeguru** [comment]
1. slogdet vs logdet
Oh... PyTorch uses the same formulation.
In Tensorflow, the logdet uses Choreskey method, but the slogdet uses LU decomposition. 
There is a complex issue...

2. logdet's flipping
We know log_det_jacobian term is not same learning curve compared with negative log-likelihood. (Here is my glow's training with Oxford 102 flower dataset.)
So I wonder it is not correct that log_det_jacobian  is always increasing... (but this is not your code and problem settings, I will monitored in your problem.)

![image](https://user-images.githubusercontent.com/30849444/84750299-10fc3080-aff6-11ea-80f5-a0d167935b56.png)
![image](https://user-images.githubusercontent.com/30849444/84750814-bdd6ad80-aff6-11ea-9cc1-124ed000f71b.png)


Anyway, thanks for  your help and reply.
